%------------------------------------------------------------------------------
% File     : LOG003_3 : TPTP v9.0.0. Released v9.0.0.
% Domain   : Alethic modal logics
% Name     : Alethic modal logic S5
% Version  : Especial.
% English  : 

% Refs     : 
% Source   : 
% Names    : 

% Syntax   : Number of formulae    :   14 (   6 unit)

% Comments : 
%------------------------------------------------------------------------------
%----Include common definitions
include('Logics/LOG001_1.l').
%----Include system definitions
include('Logics/LOG001_2.l').
%----Include alethic modal logic definitions
include('Logics/LOG003_1.l').
%------------------------------------------------------------------------------
tff(name,name,$alethic_modal_S5).

tff(make_K,axiom,$modal_system_K).

%------------------------------------------------------------------------------
